//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAI
{
    using System;
    using System.Collections.Generic;
    
    public partial class driver
    {
        public decimal id { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public string passport_serial { get; set; }
        public string passport_number { get; set; }
        public string postcode { get; set; }
        public string address { get; set; }
        public string address_life { get; set; }
        public string company { get; set; }
        public string job { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string photo { get; set; }
        public string description { get; set; }
    }
}
