//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAI
{
    using System;
    using System.Collections.Generic;
    
    public partial class region
    {
        public long id { get; set; }
        public string region_name { get; set; }
        public string subject_code { get; set; }
        public string codes { get; set; }
        public string iso3166_2 { get; set; }
    }
}
